### ISSUE TITLE
clarify where to send feedback

### ISSUE THREAD

**Issue by fin** [fin/fragdenstaat_at#2]
tell people to open bugs here, not at okfde/froide

**Comment by eest9** [comment]
In my opinion it should be clarified at the FAQs https://fragdenstaat.at/hilfe/fragen-antworten/ especially at "Wer hat FragDenStaat.at entwickelt?" because the link there mislead me to the side of the german repo.

**Comment by fin** [comment]
yep, i think the current version is better.
