### ISSUE TITLE
Lösung für E-Mails mit mehreren Antworten

### ISSUE THREAD

**Issue by eest9** [fin/fragdenstaat_at#3]
Seit der Regierung Kurz I fällt mir vermehrt auf, dass Behörden an die man mehrere eigenständige Anfragen stellt diese in einer Mail beantworten.
z.B. werden die Fragen aus https://fragdenstaat.at/anfrage/betreffend-der-trennung-von-kommunikations-und-sonstigen-daten-beim-bundestrojaner-uberwachung-verschlusselter-nachrichten/ in https://fragdenstaat.at/anfrage/betreffend-des-unabhagigen-audits-beim-bundestrojaner-uberwachung-verschlusselter-nachrichten/ mit beantwortet.

Eine Option die mir hierfür einfallen würde wäre, dass man als Anfragesteller auch vor einer 1. Antwort den Status festlegen kann. Dann könnte man in einem Abschlusskommentar festhalten wo die Antwort kam.
Eventuell könnte man aber auch die Option "Post erhalten?" dafür zweckentfremden? Dann wäre es gut dies irgendwie im UX klar zu stellen.
Andere Lösungsvorschläge?

**Comment by fin** [comment]
Ja, ich würde die Option „Post erhalten” dafür verwenden – dafür ist sie (auch) da.
Ein besserer Name für die Option fällt mir aber auch nicht ein.
