### ISSUE TITLE
Spamfilter

### ISSUE THREAD

**Issue by eest9** [fin/fragdenstaat_at#4]
siehe neueste Mail hier: https://fragdenstaat.at/anfrage/bilderberger-konferenz-2015/

**Comment by fin** [comment]
danke für den input. unser (eigentlich bisher ganz gut funktionerender) rudimentärer spamschutz hat wohl bei etwa 20% der letzten spamwelle versagt

unser mailserver fragt jetzt spamhaus, ob absender-server auf einer RBL stehen. mal sehen, ob das hilft.
